# Generated by Django 5.0.14 on 2025-12-17 12:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        ("common", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposedExtraction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("committed", "Committed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current lifecycle state",
                        max_length=20,
                    ),
                ),
                (
                    "agent_run_id",
                    models.UUIDField(
                        help_text="Unique ID for the agent execution that produced this"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        help_text="AI model identifier used for extraction",
                        max_length=100,
                    ),
                ),
                (
                    "prompt_hash",
                    models.CharField(
                        help_text="Hash of prompt template for reproducibility",
                        max_length=64,
                    ),
                ),
                (
                    "overall_confidence",
                    models.FloatField(
                        help_text="Aggregate confidence score (0.0 - 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token counts: {input, output, total}",
                    ),
                ),
                (
                    "processing_duration_ms",
                    models.PositiveIntegerField(
                        help_text="Time taken to generate proposal in milliseconds"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of review", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Reviewer comments or rejection reason"
                    ),
                ),
                (
                    "committed_action",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Action that committed this proposal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committed_extractions",
                        to="actions.action",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The source document for this extraction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_extractions",
                        to="documents.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed the proposal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant/organisation that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed Extraction",
                "verbose_name_plural": "Proposed Extractions",
                "db_table": "proposed_extractions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposedField",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("parties", "Parties/Entities"),
                            ("effective_date", "Effective Date"),
                            ("expiry_date", "Expiry/End Date"),
                            ("total_amount", "Total Amount"),
                            ("currency", "Currency"),
                            ("reference_number", "Reference Number"),
                            ("vendor", "Vendor Name"),
                            ("line_items", "Line Items"),
                            ("tax_amount", "Tax Amount"),
                            ("due_date", "Due Date"),
                            ("payment_terms", "Payment Terms"),
                            ("employee_name", "Employee Name"),
                            ("job_title", "Job Title"),
                            ("salary", "Salary/Compensation"),
                            ("start_date", "Start Date"),
                            ("governing_law", "Governing Law"),
                            ("jurisdiction", "Jurisdiction"),
                            ("termination_clause", "Termination Clause"),
                            ("policy_number", "Policy Number"),
                            ("claimant", "Claimant Name"),
                            ("claim_amount", "Claim Amount"),
                            ("custom", "Custom Field"),
                        ],
                        db_index=True,
                        help_text="Category of the field",
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Display name (may differ for CUSTOM type)",
                        max_length=100,
                    ),
                ),
                ("value", models.TextField(help_text="The extracted value as text")),
                (
                    "normalised_value",
                    models.JSONField(
                        blank=True,
                        help_text="Structured form (e.g., date as ISO, money as {amount, currency})",
                        null=True,
                    ),
                ),
                (
                    "source_text",
                    models.TextField(help_text="Original text snippet from document"),
                ),
                (
                    "source_page",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Page number where field was found",
                        null=True,
                    ),
                ),
                (
                    "source_location",
                    models.JSONField(
                        blank=True,
                        help_text="Bounding box or character offsets",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score for this field (0.0 - 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence_reason",
                    models.TextField(
                        blank=True, help_text="Explanation for confidence score"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        default="pending",
                        help_text="Validation state: pending, valid, invalid, needs_review",
                        max_length=20,
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation errors if any",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        help_text="Parent extraction proposal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="extraction.proposedextraction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed Field",
                "verbose_name_plural": "Proposed Fields",
                "db_table": "proposed_fields",
            },
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("parties", "Parties/Entities"),
                            ("effective_date", "Effective Date"),
                            ("expiry_date", "Expiry/End Date"),
                            ("total_amount", "Total Amount"),
                            ("currency", "Currency"),
                            ("reference_number", "Reference Number"),
                            ("vendor", "Vendor Name"),
                            ("line_items", "Line Items"),
                            ("tax_amount", "Tax Amount"),
                            ("due_date", "Due Date"),
                            ("payment_terms", "Payment Terms"),
                            ("employee_name", "Employee Name"),
                            ("job_title", "Job Title"),
                            ("salary", "Salary/Compensation"),
                            ("start_date", "Start Date"),
                            ("governing_law", "Governing Law"),
                            ("jurisdiction", "Jurisdiction"),
                            ("termination_clause", "Termination Clause"),
                            ("policy_number", "Policy Number"),
                            ("claimant", "Claimant Name"),
                            ("claim_amount", "Claim Amount"),
                            ("custom", "Custom Field"),
                        ],
                        db_index=True,
                        help_text="Category of the field",
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(help_text="Display name", max_length=100),
                ),
                ("value", models.TextField(help_text="The committed value as text")),
                (
                    "normalised_value",
                    models.JSONField(
                        blank=True, help_text="Structured form", null=True
                    ),
                ),
                (
                    "source_text",
                    models.TextField(help_text="Original text snippet from document"),
                ),
                (
                    "source_page",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Page number where field was found",
                        null=True,
                    ),
                ),
                (
                    "source_location",
                    models.JSONField(
                        blank=True,
                        help_text="Bounding box or character offsets",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score at time of commit",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "committed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of commit"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False when rolled back (soft delete)",
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when deactivated by rollback",
                        null=True,
                    ),
                ),
                (
                    "committed_action",
                    models.ForeignKey(
                        help_text="Reference to the commit Action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fields",
                        to="actions.action",
                    ),
                ),
                (
                    "committed_by",
                    models.ForeignKey(
                        help_text="User who committed the field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committed_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by_action",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the rollback Action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deactivated_fields",
                        to="actions.action",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The source document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="documents.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant/organisation that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="common.tenant",
                    ),
                ),
                (
                    "source_proposal",
                    models.ForeignKey(
                        help_text="The proposal this field was committed from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committed_fields",
                        to="extraction.proposedextraction",
                    ),
                ),
                (
                    "source_proposed_field",
                    models.ForeignKey(
                        help_text="The specific proposed field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committed_as",
                        to="extraction.proposedfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Field",
                "verbose_name_plural": "Extracted Fields",
                "db_table": "extracted_fields",
            },
        ),
        migrations.AddIndex(
            model_name="proposedextraction",
            index=models.Index(
                fields=["tenant", "status"], name="ix_proposals_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="proposedextraction",
            index=models.Index(
                fields=["document", "status"], name="ix_proposals_document_status"
            ),
        ),
        migrations.AddIndex(
            model_name="proposedextraction",
            index=models.Index(
                fields=["agent_run_id"], name="ix_proposals_agent_run_id"
            ),
        ),
        migrations.AddIndex(
            model_name="proposedextraction",
            index=models.Index(fields=["created_at"], name="ix_proposals_created_at"),
        ),
        migrations.AddIndex(
            model_name="proposedfield",
            index=models.Index(
                fields=["extraction", "field_type"], name="ix_proposed_fields_ext_type"
            ),
        ),
        migrations.AddIndex(
            model_name="proposedfield",
            index=models.Index(
                fields=["confidence"], name="ix_proposed_fields_confidence"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposedfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("field_type", "custom"), _negated=True),
                fields=("extraction", "field_type"),
                name="unique_field_type_per_extraction",
            ),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(
                fields=["tenant", "document"], name="ix_extracted_tenant_document"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(
                fields=["document", "field_type", "is_active"],
                name="ix_extracted_doc_type_active",
            ),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(
                fields=["committed_at"], name="ix_extracted_committed_at"
            ),
        ),
    ]
