# Generated by Django 5.0.14 on 2025-12-17 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("extraction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this template version",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this template or changes made",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="Document type this applies to (null = default for all)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System message sent to the AI model"),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User message template. Use {placeholders} for dynamic content"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the active template for its document type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant/organisation that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="common.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "db_table": "prompt_templates",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="ix_prompts_tenant_active"
                    ),
                    models.Index(
                        fields=["document_type", "is_active"],
                        name="ix_prompts_doctype_active",
                    ),
                ],
            },
        ),
    ]
