# Generated by Django 5.0.14 on 2025-12-17 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("commit_extraction", "Commit Extraction"),
                            ("rollback_extraction", "Rollback Extraction"),
                            ("reject_extraction", "Reject Extraction"),
                            ("update_field", "Update Field"),
                            ("delete_field", "Delete Field"),
                            ("document_upload", "Document Upload"),
                            ("document_delete", "Document Delete"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="completed",
                        help_text="Completion status of the action",
                        max_length=20,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        default="user",
                        help_text="Category of actor: user, system, or celery_task",
                        max_length=20,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        help_text="User ID or system identifier", max_length=100
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Denormalised email for readability in audit logs",
                        max_length=254,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Model class name of the affected entity",
                        max_length=100,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="Primary key of the affected entity", max_length=100
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="Tenant where action occurred"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        db_index=True,
                        help_text="Request trace ID for correlation across services",
                        max_length=100,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Unique key to prevent duplicate actions from retries",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "pre_state",
                    models.JSONField(
                        default=dict,
                        help_text="JSONB snapshot of state before mutation",
                    ),
                ),
                (
                    "post_state",
                    models.JSONField(
                        default=dict, help_text="JSONB snapshot of state after mutation"
                    ),
                ),
                (
                    "is_reversible",
                    models.BooleanField(
                        default=True, help_text="Whether this action can be rolled back"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (agent_run_id, model_version, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if status is FAILED"
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The action that reversed this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverses_set",
                        to="actions.action",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text="The action that this one reverses",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by_set",
                        to="actions.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "db_table": "actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "action_type"],
                        name="ix_actions_tenant_type",
                    ),
                    models.Index(
                        fields=["tenant_id", "created_at"],
                        name="ix_actions_tenant_created",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="ix_actions_target"
                    ),
                    models.Index(fields=["trace_id"], name="ix_actions_trace_id"),
                    models.Index(fields=["actor_id"], name="ix_actions_actor_id"),
                ],
            },
        ),
    ]
