# Generated by Django 5.0.14 on 2025-12-17 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded document file",
                        upload_to="documents/%Y/%m/%d/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename from upload", max_length=255
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="MIME type or extension (e.g., pdf, docx)",
                        max_length=50,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash for deduplication and integrity",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("extracted", "Extracted"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable status details (e.g., error message)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Document title (extracted or user-provided)",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional document metadata",
                    ),
                ),
                (
                    "extraction_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when extraction processing began",
                        null=True,
                    ),
                ),
                (
                    "extraction_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when extraction processing completed",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant/organisation that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="common.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="ix_documents_tenant_status"
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="ix_documents_tenant_created",
                    ),
                    models.Index(fields=["file_hash"], name="ix_documents_file_hash"),
                    models.Index(
                        fields=["uploaded_by"], name="ix_documents_uploaded_by"
                    ),
                ],
            },
        ),
    ]
