# Generated by Django 5.0.14 on 2025-12-17 12:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Flag identifier (e.g., 'ai_extraction_enabled')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this flag controls"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch - if False, flag is disabled for everyone",
                    ),
                ),
                (
                    "rollout_percentage",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage of tenants who see this enabled (0-100)",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "enabled_tenants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tenant UUIDs where flag is always enabled",
                    ),
                ),
                (
                    "disabled_tenants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tenant UUIDs where flag is always disabled",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="Team or person responsible for this flag",
                        max_length=100,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Auto-disable after this time", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "db_table": "feature_flags",
                "indexes": [
                    models.Index(fields=["key"], name="ix_feature_flags_key"),
                    models.Index(
                        fields=["is_enabled"], name="ix_feature_flags_enabled"
                    ),
                ],
            },
        ),
    ]
